### ISSUE TITLE
기존 장소와 추천 장소 마커 동일하게 표시

### ISSUE THREAD

**Issue by Lluora** [Lluora/Team14#13]
검색)
기존 장소와 추천 장소 마커 동일하게 표시

**Comment by haedal-uni** [comment]
#### 구현 기능
- 좋아요 +1 제한
- 추천장소 마커 클릭 시 장소 이름과 주소 띄우기
<br>

<img src = https://user-images.githubusercontent.com/74857364/137246319-0d426149-709b-4496-b87b-83a7fca547c1.gif width="70%">

<br>

`*` 추천 장소 클릭 시 해당 위치로 이동하는 것은 미구현

**Comment by haedal-uni** [comment]
develop merge로 issue 종료합니다
