### ISSUE TITLE
좋아요 +1 제한 및 취소

### ISSUE THREAD

**Issue by Lluora** [Lluora/Team14#24]
좋아요)
좋아요 +1 제한 및 취소

**Comment by haedal-uni** [comment]
웹 프로그래밍 A-Z 심화 Training 강의 듣는 중 입니다.

**Comment by haedal-uni** [comment]
@manijang2 @pouryourlove @YuJehyeop 

<br>

<img src = https://user-images.githubusercontent.com/74857364/136918215-94ab4d65-2b20-4a9a-869c-a30fc2ad2af8.png width="70%">

위와 같이 로그인을 하면 아래와 같이 url주소가 바뀌게 하려고 하는데
<br>

![image](https://user-images.githubusercontent.com/74857364/136917979-7bf4a370-85e9-4cf6-9358-9bb09bba247b.png)

<br>

크롬에서는 실행이 잘 되는데 웨일로 실행했을 때는 실행이 안됩니다.
브라우저에 같은 결과 값을 띄우고 싶은데 어떻게 하면 좋을까요??

**Comment by haedal-uni** [comment]
1차 프로젝트 코드에서 좋아요 수 제한만 작성한 코드입니다.
<br>

![AC_ 20211013-001944  (1)](https://user-images.githubusercontent.com/74857364/136984615-d3b225a6-2f19-4057-9908-27490895eb4a.gif)

<br>

id가 ___인 db를 가지고 와서 좋아요 버튼 클릭 시 like를 +-1, 총 like 수 띄우기 기능 구현 예정
심화 강의_회원가입 듣고 진행할 예정

**Comment by manijang2** [comment]
굿굿! @Lluora

**Comment by haedal-uni** [comment]
#### 구현 기능
##### 전체 추천 장소 띄우기 부분
- db 직접 구축 후 고정 id 별로 좋아요 누른 경우 ❤ 버튼, 좋아요 누르지 않은 경우 🤍 버튼 띄우기
- 총 좋아요 개수 띄우기
- 반려동물 & 전체 장소 띄우기 버튼, 좋아요 버튼 css 수정 

<br>

#### 보완해야할 점
`*` 반려동물 동반 가능 장소도 위와 동일한 기능 구현
`*` 직접 id를 입력 값으로 받아서 좋아요 버튼 띄우기

**Comment by haedal-uni** [comment]
#### 구현기능
a 장소 반려동물 동반 가능 체크 수 / a장소 총 리뷰 수 → ***percent*** 로 db 저장
percent가 50 이상인 경우에만 반려동물 동반 가능 장소 추천 리스트로 띄우기

<br>

<img src = https://user-images.githubusercontent.com/74857364/137430854-7cd51e4d-209a-42ff-8a03-f4bc55965794.gif width="40%">

**Comment by haedal-uni** [comment]
develop branch merge
